# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            thinkxl 
tagline:          Mostly CSS, JavaScript, and Python
url:              http://thinkxl.codes
paginate:         4
baseurl:          /
author:
  name:           Juan Olvera 
  url:            https://twitter.com/thinkxl
  email:          thinkxl@gmail.com 

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/thinkxl/thinkxl.github.io

sass:
    style: :compressed

# Plugins 
# gems:
